# Generated by Django 4.2.7 on 2025-06-25 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('accounts', 'Accounts'), ('admin', 'Admin'), ('business_development_manager', 'Business Development Manager'), ('business_development_associate', 'Business Development Associate'), ('credit_manager', 'Credit Manager'), ('super_user', 'Super User'), ('broker', 'Broker'), ('bd', 'Business Development'), ('client', 'Client')], default='client', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status_in_app', models.BooleanField(default=True)),
                ('stage_change_in_app', models.BooleanField(default=True)),
                ('repayment_upcoming_in_app', models.BooleanField(default=True)),
                ('repayment_overdue_in_app', models.BooleanField(default=True)),
                ('note_reminder_in_app', models.BooleanField(default=True)),
                ('document_uploaded_in_app', models.BooleanField(default=True)),
                ('signature_required_in_app', models.BooleanField(default=True)),
                ('system_in_app', models.BooleanField(default=True)),
                ('active_loan_payment_in_app', models.BooleanField(default=True)),
                ('active_loan_expiry_in_app', models.BooleanField(default=True)),
                ('active_loan_critical_in_app', models.BooleanField(default=True)),
                ('active_loan_manual_in_app', models.BooleanField(default=True)),
                ('application_status_email', models.BooleanField(default=True)),
                ('stage_change_email', models.BooleanField(default=True)),
                ('repayment_upcoming_email', models.BooleanField(default=True)),
                ('repayment_overdue_email', models.BooleanField(default=True)),
                ('note_reminder_email', models.BooleanField(default=True)),
                ('document_uploaded_email', models.BooleanField(default=False)),
                ('signature_required_email', models.BooleanField(default=True)),
                ('system_email', models.BooleanField(default=False)),
                ('active_loan_payment_email', models.BooleanField(default=True)),
                ('active_loan_expiry_email', models.BooleanField(default=True)),
                ('active_loan_critical_email', models.BooleanField(default=True)),
                ('active_loan_manual_email', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('application_status', 'Application Status Change'), ('stage_change', 'Stage Change'), ('repayment_upcoming', 'Repayment Upcoming'), ('repayment_overdue', 'Repayment Overdue'), ('note_reminder', 'Note Reminder'), ('document_uploaded', 'Document Uploaded'), ('signature_required', 'Signature Required'), ('system', 'System Notification'), ('active_loan_payment', 'Active Loan Payment Alert'), ('active_loan_expiry', 'Active Loan Expiry Alert'), ('active_loan_critical', 'Active Loan Critical Alert'), ('active_loan_manual', 'Active Loan Manual Alert')], max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('email_type', models.CharField(blank=True, max_length=100, null=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
