# Generated by Django 4.2.7 on 2025-06-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('admin', 'Admin'), ('business_development_manager', 'Business Development Manager'), ('business_development_associate', 'Business Development Associate'), ('credit_manager', 'Credit Manager'), ('super_user', 'Super User'), ('broker', 'Broker'), ('bd', 'Business Development'), ('client', 'Client')], default='client', max_length=30),
        ),
    ]
