# Generated by Django 4.2.7 on 2025-06-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_status', 'Application Status Change'), ('repayment_upcoming', 'Repayment Upcoming'), ('repayment_overdue', 'Repayment Overdue'), ('note_reminder', 'Note Reminder'), ('document_uploaded', 'Document Uploaded'), ('signature_required', 'Signature Required'), ('system', 'System Notification'), ('active_loan_payment', 'Active Loan Payment Alert'), ('active_loan_expiry', 'Active Loan Expiry Alert'), ('active_loan_critical', 'Active Loan Critical Alert'), ('active_loan_manual', 'Active Loan Manual Alert')], max_length=50),
        ),
    ]
