# Generated by Django 4.2.7 on 2025-06-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notificationpreference_active_loan_critical_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[
                ('application_status', 'Application Status Change'),
                ('stage_change', 'Stage Change'),
                ('repayment_upcoming', 'Repayment Upcoming'),
                ('repayment_overdue', 'Repayment Overdue'),
                ('note_reminder', 'Note Reminder'),
                ('document_uploaded', 'Document Uploaded'),
                ('signature_required', 'Signature Required'),
                ('system', 'System Notification'),
                ('active_loan_payment', 'Active Loan Payment Alert'),
                ('active_loan_expiry', 'Active Loan Expiry Alert'),
                ('active_loan_critical', 'Active Loan Critical Alert'),
                ('active_loan_manual', 'Active Loan Manual Alert')
            ], max_length=50),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='stage_change_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='stage_change_email',
            field=models.BooleanField(default=True),
        ),
    ] 