# Generated by Django 4.2.7 on 2025-06-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('client', 'Client'), ('bdm', 'Business Development Manager'), ('broker', 'Broker'), ('custom', 'Custom Email')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('send_datetime', models.DateTimeField()),
                ('email_body', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['send_datetime'],
            },
        ),
    ]
