# Generated by Django 4.2.7 on 2025-06-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BDM',
                'verbose_name_plural': 'BDMs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, help_text='DEPRECATED: Address field is no longer used', null=True)),
                ('phone', models.CharField(blank=True, help_text='DEPRECATED: Phone field is no longer used', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='DEPRECATED: Email field is no longer used', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch/Subsidiary',
                'verbose_name_plural': 'Branches/Subsidiaries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('commission_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('commission_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('commission_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('commission_bsb', models.CharField(blank=True, max_length=10, null=True)),
                ('commission_account_locked', models.BooleanField(default=False, help_text='If True, only super user and accounts can modify commission details')),
                ('commission_account_locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bdms', models.ManyToManyField(blank=True, related_name='bdm_brokers', to='brokers.bdm')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_brokers', to='brokers.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
