# Generated by Django 4.2.7 on 2025-06-25 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='commission_account_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_commission_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brokers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bdm',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_bdms', to='brokers.branch'),
        ),
        migrations.AddField(
            model_name='bdm',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bdms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bdm',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdm_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
