# Generated by Django 4.2.7 on 2025-06-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_alter_bdm_options_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Branch/Subsidiary', 'verbose_name_plural': 'Branches/Subsidiaries'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, help_text='DEPRECATED: Address field is no longer used', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, help_text='DEPRECATED: Email field is no longer used', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, help_text='DEPRECATED: Phone field is no longer used', max_length=20, null=True),
        ),
    ]
