# Generated by Django 4.2.7 on 2025-06-23 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brokers', '0004_simplify_branch_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='commission_account_locked',
            field=models.BooleanField(default=False, help_text='If True, only super user and accounts can modify commission details'),
        ),
        migrations.AddField(
            model_name='broker',
            name='commission_account_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='commission_account_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_commission_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
