# Generated by Django 4.2.7 on 2025-06-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('casual', 'Casual'), ('self_employed', 'Self Employed'), ('contractor', 'Contractor'), ('unemployed', 'Unemployed'), ('retired', 'Retired')], max_length=20, null=True),
        ),
    ]
