# Generated by Django 4.2.7 on 2025-05-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0005_add_bg_type_to_assets_liabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('Property', 'Property'), ('Vehicle', 'Vehicle'), ('Savings', 'Savings'), ('Investment Shares', 'Investment Shares'), ('Credit Card', 'Credit Card'), ('Other Creditor', 'Other Creditor'), ('Other', 'Other'), ('To be refinanced', 'To be refinanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='bg_type',
            field=models.CharField(blank=True, choices=[('BG1', 'BG1'), ('BG2', 'BG2')], help_text='Indicates if this asset belongs to BG1 or BG2 (only for guarantor assets)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
