# Generated by Django 4.2.7 on 2025-06-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0006_alter_asset_address_alter_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='is_smsf_trustee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='is_trustee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
