# Generated by Django 4.2.7 on 2025-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0007_alter_borrower_is_smsf_trustee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description_if_applicable',
            field=models.TextField(blank=True, help_text="Additional description required when asset_type is 'Other'", null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='is_smsf_trustee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='is_trustee',
            field=models.BooleanField(default=False),
        ),
    ]
