# Generated by Django 4.2.7 on 2025-06-25 13:41

from django.db import migrations, models


def convert_to_be_refinanced_to_other(apps, schema_editor):
    """
    Convert existing assets with 'To be refinanced' asset type to 'Other' type
    """
    Asset = apps.get_model('borrowers', 'Asset')
    
    # Find all assets with 'To be refinanced' asset type
    to_be_refinanced_assets = Asset.objects.filter(asset_type='To be refinanced')
    
    # Convert them to 'Other' type
    for asset in to_be_refinanced_assets:
        asset.asset_type = 'Other'
        # Update description to indicate it was originally "To be refinanced"
        if asset.description:
            asset.description = f"Originally 'To be refinanced': {asset.description}"
        else:
            asset.description = "Originally 'To be refinanced'"
        asset.save()


def reverse_convert_to_be_refinanced_to_other(apps, schema_editor):
    """
    Reverse migration - convert 'Other' assets back to 'To be refinanced' if they were originally that type
    """
    Asset = apps.get_model('borrowers', 'Asset')
    
    # Find assets that were converted from 'To be refinanced'
    converted_assets = Asset.objects.filter(
        asset_type='Other',
        description__startswith="Originally 'To be refinanced'"
    )
    
    # Convert them back to 'To be refinanced'
    for asset in converted_assets:
        asset.asset_type = 'To be refinanced'
        # Remove the prefix from description
        if asset.description.startswith("Originally 'To be refinanced': "):
            asset.description = asset.description[35:]  # Remove prefix
        elif asset.description == "Originally 'To be refinanced'":
            asset.description = ""
        asset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0008_add_description_if_applicable_to_asset'),
    ]

    operations = [
        # Data migration to convert existing 'To be refinanced' assets to 'Other'
        migrations.RunPython(
            convert_to_be_refinanced_to_other,
            reverse_convert_to_be_refinanced_to_other
        ),
        # Schema migration to remove the choice from the field
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('Property', 'Property'), ('Vehicle', 'Vehicle'), ('Savings', 'Savings'), ('Investment Shares', 'Investment Shares'), ('Credit Card', 'Credit Card'), ('Other Creditor', 'Other Creditor'), ('Other', 'Other')], max_length=20),
        ),
    ]
