# Generated by Django 4.2.7 on 2025-06-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0009_remove_to_be_refinanced_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='description_if_applicable',
        ),
    ]
