# Generated by Django 4.2.7 on 2025-06-25 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0001_initial'),
        ('applications', '0001_initial'),
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityproperty',
            name='application',
            field=models.ForeignKey(help_text='The application this property secures', on_delete=django.db.models.deletion.CASCADE, related_name='security_properties', to='applications.application'),
        ),
        migrations.AddField(
            model_name='securityproperty',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='application',
            field=models.ForeignKey(blank=True, help_text='The application this repayment belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_repayments', to='applications.application'),
        ),
        migrations.AddField(
            model_name='quantitysurveyor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrequirement',
            name='application',
            field=models.ForeignKey(help_text='The application this requirement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='loan_requirements', to='applications.application'),
        ),
        migrations.AddField(
            model_name='loanrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingcalculationhistory',
            name='application',
            field=models.ForeignKey(help_text='The application this calculation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='funding_calculations', to='applications.application'),
        ),
        migrations.AddField(
            model_name='fundingcalculationhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fee',
            name='application',
            field=models.ForeignKey(blank=True, help_text='The application this fee belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_fees', to='applications.application'),
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, help_text='The application this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_documents', to='applications.application'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_bd',
            field=models.ForeignKey(blank=True, help_text='Assigned BD user for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='bd',
            field=models.ForeignKey(help_text='Business Development Manager for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdm_applications', to='brokers.bdm'),
        ),
        migrations.AddField(
            model_name='application',
            name='borrowers',
            field=models.ManyToManyField(blank=True, help_text='Borrowers associated with this application', related_name='borrower_applications', to='borrowers.borrower'),
        ),
        migrations.AddField(
            model_name='application',
            name='branch',
            field=models.ForeignKey(help_text='Branch associated with this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_applications', to='brokers.branch'),
        ),
        migrations.AddField(
            model_name='application',
            name='broker',
            field=models.ForeignKey(help_text='Broker handling this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_applications', to='brokers.broker'),
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='guarantors',
            field=models.ManyToManyField(blank=True, help_text='Guarantors for this application', related_name='guaranteed_applications', to='borrowers.guarantor'),
        ),
        migrations.AddField(
            model_name='application',
            name='quantity_surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.quantitysurveyor'),
        ),
        migrations.AddField(
            model_name='application',
            name='valuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.valuer'),
        ),
        migrations.AddField(
            model_name='activeloanrepayment',
            name='active_loan',
            field=models.ForeignKey(help_text='Active loan this repayment is for', on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='applications.activeloan'),
        ),
        migrations.AddField(
            model_name='activeloan',
            name='application',
            field=models.OneToOneField(help_text='Application that has been settled and become an active loan', on_delete=django.db.models.deletion.CASCADE, related_name='active_loan', to='applications.application'),
        ),
        migrations.AddIndex(
            model_name='valuer',
            index=models.Index(fields=['company_name'], name='application_company_28f661_idx'),
        ),
        migrations.AddIndex(
            model_name='valuer',
            index=models.Index(fields=['is_active'], name='application_is_acti_48541c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityproperty',
            index=models.Index(fields=['application'], name='application_applica_2cc3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='securityproperty',
            index=models.Index(fields=['property_type'], name='application_propert_88f107_idx'),
        ),
        migrations.AddIndex(
            model_name='securityproperty',
            index=models.Index(fields=['address_suburb', 'address_state'], name='application_address_9051b8_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['application'], name='application_applica_e142e8_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['status'], name='application_status_b5c942_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['due_date'], name='application_due_dat_825548_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['paid_date'], name='application_paid_da_0cd72b_idx'),
        ),
        migrations.AddIndex(
            model_name='quantitysurveyor',
            index=models.Index(fields=['company_name'], name='application_company_8d5561_idx'),
        ),
        migrations.AddIndex(
            model_name='quantitysurveyor',
            index=models.Index(fields=['is_active'], name='application_is_acti_22e639_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequirement',
            index=models.Index(fields=['application'], name='application_applica_b1bebb_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingcalculationhistory',
            index=models.Index(fields=['application'], name='application_applica_e592cf_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['application'], name='application_applica_5e13b2_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['fee_type'], name='application_fee_typ_a099ad_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['status'], name='application_status_02d633_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['due_date'], name='application_due_dat_0fba4a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['application'], name='application_applica_824c17_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='application_documen_57c184_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='application_uploade_798c28_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['reference_number'], name='application_referen_56abf0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['stage'], name='application_stage_264235_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['broker'], name='application_broker__61de8e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['bd'], name='application_bd_id_2550af_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c6d08d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['estimated_settlement_date'], name='application_estimat_b36d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_archived'], name='application_is_arch_2b9bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='activeloanrepayment',
            index=models.Index(fields=['active_loan'], name='application_active__56e062_idx'),
        ),
        migrations.AddIndex(
            model_name='activeloanrepayment',
            index=models.Index(fields=['payment_date'], name='application_payment_7b5cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='activeloanrepayment',
            index=models.Index(fields=['due_date'], name='application_due_dat_779de4_idx'),
        ),
        migrations.AddIndex(
            model_name='activeloanrepayment',
            index=models.Index(fields=['repayment_type'], name='application_repayme_1c0a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='activeloan',
            index=models.Index(fields=['application'], name='application_applica_d45a79_idx'),
        ),
        migrations.AddIndex(
            model_name='activeloan',
            index=models.Index(fields=['settlement_date'], name='application_settlem_e4f7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='activeloan',
            index=models.Index(fields=['loan_expiry_date'], name='application_loan_ex_8b9315_idx'),
        ),
        migrations.AddIndex(
            model_name='activeloan',
            index=models.Index(fields=['is_active'], name='application_is_acti_688247_idx'),
        ),
    ]
