# Generated by Django 4.2.7 on 2025-06-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='funding_calculation_input',
            field=models.JSONField(blank=True, help_text='Stores the funding calculation input parameters', null=True),
        ),
    ]
