# Generated by Django 4.2.7 on 2025-05-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_application_has_been_bankrupt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_been_bankrupt',
            field=models.BooleanField(default=False, help_text='Have the Borrower(s) and the Guarantor(s) been bankrupt or insolvent in the past 5 years?'),
        ),
        migrations.AddField(
            model_name='application',
            name='has_been_refused_credit',
            field=models.BooleanField(default=False, help_text='Has the Borrower(s) and the Guarantor(s) been refused credit by a credit provider in the last 1 year?'),
        ),
        migrations.AddField(
            model_name='application',
            name='has_outstanding_ato_debt',
            field=models.BooleanField(default=False, help_text='Are there any outstanding debts current or otherwise due to the ATO by the Borrower(s) and the Guarantor(s)?'),
        ),
        migrations.AddField(
            model_name='application',
            name='has_outstanding_tax_returns',
            field=models.BooleanField(default=False, help_text='Does the Borrower(s) and the Guarantor(s) have outstanding Tax or BAS returns due to be lodged with the ATO?'),
        ),
        migrations.AddField(
            model_name='application',
            name='has_payment_arrangements',
            field=models.BooleanField(default=False, help_text='Has the Borrower(s) and the Guarantor(s) made payment arrangements with a creditor to payout debt that is still current?'),
        ),
        migrations.AddField(
            model_name='application',
            name='has_pending_litigation',
            field=models.BooleanField(default=False, help_text='Do the Borrower(s) and the Guarantor(s) have any pending or past litigation matters (within the last 2 years)?'),
        ),
        migrations.AddField(
            model_name='application',
            name='has_unsatisfied_judgements',
            field=models.BooleanField(default=False, help_text='Are there any unsatisfied judgements against the Borrower(s) and the Guarantor(s)?'),
        ),
        migrations.AddField(
            model_name='application',
            name='solvency_enquiries_details',
            field=models.TextField(blank=True, help_text="Additional details for any 'Yes' answers to solvency enquiries", null=True),
        ),
    ]
