# Generated by Django 4.2.7 on 2025-06-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_application_assigned_bd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='has_been_bankrupt',
            field=models.BooleanField(blank=True, default=None, help_text='Have the Borrower(s) and the Guarantor(s) been bankrupt or insolvent in the past 5 years?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_been_refused_credit',
            field=models.BooleanField(blank=True, default=None, help_text='Has the Borrower(s) and the Guarantor(s) been refused credit by a credit provider in the last 1 year?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_outstanding_ato_debt',
            field=models.BooleanField(blank=True, default=None, help_text='Are there any outstanding debts current or otherwise due to the ATO by the Borrower(s) and the Guarantor(s)?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_outstanding_tax_returns',
            field=models.BooleanField(blank=True, default=None, help_text='Does the Borrower(s) and the Guarantor(s) have outstanding Tax or BAS returns due to be lodged with the ATO?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_payment_arrangements',
            field=models.BooleanField(blank=True, default=None, help_text='Has the Borrower(s) and the Guarantor(s) made payment arrangements with a creditor to payout debt that is still current?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_pending_litigation',
            field=models.BooleanField(blank=True, default=None, help_text='Do the Borrower(s) and the Guarantor(s) have any pending or past litigation matters (within the last 2 years)?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_unsatisfied_judgements',
            field=models.BooleanField(blank=True, default=None, help_text='Are there any unsatisfied judgements against the Borrower(s) and the Guarantor(s)?', null=True),
        ),
        migrations.AlterField(
            model_name='loanrequirement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequirement',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
