# Generated by Django 4.2.7 on 2025-06-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_remove_required_field_validations'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type_other',
            field=models.TextField(blank=True, help_text="Details for 'Other' application type", null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(blank=True, choices=[('acquisition', 'Acquisition'), ('refinance', 'Refinance'), ('equity_release', 'Equity Release'), ('refinance_equity_release', 'Refinance & Equity Release'), ('second_mortgage', '2nd Mortgage'), ('caveat', 'Caveat'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
