# Generated by Django 4.2.7 on 2025-06-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_update_application_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='capitalised_interest_term',
            field=models.PositiveIntegerField(blank=True, help_text='Capitalised Interest Term in months', null=True),
        ),
    ]
