# Generated by Django 4.2.7 on 2025-06-18 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0017_application_capitalised_interest_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the valuation company', max_length=255)),
                ('contact_name', models.CharField(help_text='Name of the contact person', max_length=255)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Company address', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this valuer', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this valuer is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_valuers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valuer',
                'verbose_name_plural': 'Valuers',
                'ordering': ['company_name', 'contact_name'],
            },
        ),
        migrations.CreateModel(
            name='QuantitySurveyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the QS company', max_length=255)),
                ('contact_name', models.CharField(help_text='Name of the contact person', max_length=255)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Company address', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this QS', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this QS is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quantity_surveyors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quantity Surveyor',
                'verbose_name_plural': 'Quantity Surveyors',
                'ordering': ['company_name', 'contact_name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='quantity_surveyor',
            field=models.ForeignKey(blank=True, help_text='Selected quantity surveyor for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.quantitysurveyor'),
        ),
        migrations.AddField(
            model_name='application',
            name='valuer',
            field=models.ForeignKey(blank=True, help_text='Selected valuer for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.valuer'),
        ),
    ]
