# Generated by Django 4.2.7 on 2025-06-19 14:52

import applications.models.core
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_alter_bdm_options_alter_branch_options_and_more'),
        ('borrowers', '0006_alter_asset_address_alter_asset_asset_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0018_add_valuer_and_qs_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fee', 'verbose_name_plural': 'Fees'},
        ),
        migrations.AlterModelOptions(
            name='fundingcalculationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Funding Calculation History', 'verbose_name_plural': 'Funding Calculation Histories'},
        ),
        migrations.AlterModelOptions(
            name='loanrequirement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loan Requirement', 'verbose_name_plural': 'Loan Requirements'},
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Repayment', 'verbose_name_plural': 'Repayments'},
        ),
        migrations.AlterModelOptions(
            name='securityproperty',
            options={'ordering': ['-created_at'], 'verbose_name': 'Security Property', 'verbose_name_plural': 'Security Properties'},
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AddField(
            model_name='fundingcalculationhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='application',
            name='additional_comments',
            field=models.TextField(blank=True, help_text='Additional comments about the loan', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(blank=True, choices=[('acquisition', 'Acquisition'), ('refinance', 'Refinance'), ('equity_release', 'Equity Release'), ('refinance_equity_release', 'Refinance & Equity Release'), ('second_mortgage', '2nd Mortgage'), ('caveat', 'Caveat'), ('other', 'Other')], help_text='Type of loan application', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='assigned_bd',
            field=models.ForeignKey(blank=True, help_text='Assigned BD user for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='bd',
            field=models.ForeignKey(help_text='Business Development Manager for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdm_applications', to='brokers.bdm'),
        ),
        migrations.AlterField(
            model_name='application',
            name='borrowers',
            field=models.ManyToManyField(blank=True, help_text='Borrowers associated with this application', related_name='borrower_applications', to='borrowers.borrower'),
        ),
        migrations.AlterField(
            model_name='application',
            name='branch',
            field=models.ForeignKey(help_text='Branch associated with this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_applications', to='brokers.branch'),
        ),
        migrations.AlterField(
            model_name='application',
            name='broker',
            field=models.ForeignKey(help_text='Broker handling this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_applications', to='brokers.broker'),
        ),
        migrations.AlterField(
            model_name='application',
            name='capitalised_interest_term',
            field=models.PositiveIntegerField(blank=True, help_text='Capitalised interest term in months', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='estimated_settlement_date',
            field=models.DateField(blank=True, help_text='Expected settlement date', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='exit_strategy',
            field=models.CharField(blank=True, choices=[('sale', 'Sale of Property'), ('refinance', 'Refinance'), ('income', 'Income/Cash Flow'), ('other', 'Other')], help_text='Planned exit strategy for the loan', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='exit_strategy_details',
            field=models.TextField(blank=True, help_text='Additional details about exit strategy', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='guarantors',
            field=models.ManyToManyField(blank=True, help_text='Guarantors for this application', related_name='guaranteed_applications', to='borrowers.guarantor'),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_been_bankrupt',
            field=models.BooleanField(blank=True, default=None, help_text='Have the Borrower(s) and Guarantor(s) been bankrupt or insolvent in the past 5 years?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_been_refused_credit',
            field=models.BooleanField(blank=True, default=None, help_text='Has the Borrower(s) and Guarantor(s) been refused credit by a credit provider in the last 1 year?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_outstanding_ato_debt',
            field=models.BooleanField(blank=True, default=None, help_text='Are there any outstanding debts current or otherwise due to the ATO by the Borrower(s) and Guarantor(s)?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_outstanding_tax_returns',
            field=models.BooleanField(blank=True, default=None, help_text='Does the Borrower(s) and Guarantor(s) have outstanding Tax or BAS returns due to be lodged with the ATO?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_payment_arrangements',
            field=models.BooleanField(blank=True, default=None, help_text='Has the Borrower(s) and Guarantor(s) made payment arrangements with a creditor to payout debt that is still current?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_pending_litigation',
            field=models.BooleanField(blank=True, default=None, help_text='Do the Borrower(s) and Guarantor(s) have any pending or past litigation matters (within the last 2 years)?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_unsatisfied_judgements',
            field=models.BooleanField(blank=True, default=None, help_text='Are there any unsatisfied judgements against the Borrower(s) and Guarantor(s)?', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate as percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Requested loan amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='loan_purpose',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('refinance', 'Refinance'), ('construction', 'Construction'), ('equity_release', 'Equity Release'), ('debt_consolidation', 'Debt Consolidation'), ('business_expansion', 'Business Expansion'), ('working_capital', 'Working Capital'), ('other', 'Other')], help_text='Specific purpose of the loan', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='prior_application',
            field=models.BooleanField(default=False, help_text='Whether there was a prior application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='prior_application_details',
            field=models.TextField(blank=True, help_text='Details about prior applications', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='product_id',
            field=models.CharField(blank=True, help_text='Product identifier', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='purpose',
            field=models.TextField(blank=True, default='', help_text='General purpose of the application', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='qs_company_name',
            field=models.CharField(blank=True, help_text='[Legacy] QS company name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='qs_contact_name',
            field=models.CharField(blank=True, help_text='[Legacy] QS contact person name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='qs_email',
            field=models.EmailField(blank=True, help_text='[Legacy] QS email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='qs_phone',
            field=models.CharField(blank=True, help_text='[Legacy] QS phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='qs_report_date',
            field=models.DateField(blank=True, help_text='Date of QS report', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='quantity_surveyor',
            field=models.ForeignKey(blank=True, help_text='Selected quantity surveyor for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qs_applications', to='applications.quantitysurveyor'),
        ),
        migrations.AlterField(
            model_name='application',
            name='reference_number',
            field=models.CharField(default=applications.models.core.generate_reference_number, help_text='Unique reference number for this application', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='repayment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', help_text='How often repayments are made', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='security_address',
            field=models.TextField(blank=True, help_text='[Legacy] Security property address', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='security_type',
            field=models.CharField(blank=True, help_text='[Legacy] Security property type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='security_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[Legacy] Security property value', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='signature_date',
            field=models.DateField(blank=True, help_text='Date the application was signed', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='signed_by',
            field=models.CharField(blank=True, help_text='Name of person who signed the application', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('sent_to_lender', 'Sent to Lender'), ('funding_table_issued', 'Funding Table Issued'), ('iloo_issued', 'ILOO Issued'), ('iloo_signed', 'ILOO Signed'), ('commitment_fee_paid', 'Commitment Fee Paid'), ('app_submitted', 'App Submitted'), ('valuation_ordered', 'Valuation Ordered'), ('valuation_received', 'Valuation Received'), ('more_info_required', 'More Info Required'), ('formal_approval', 'Formal Approval'), ('loan_docs_instructed', 'Loan Docs Instructed'), ('loan_docs_issued', 'Loan Docs Issued'), ('loan_docs_signed', 'Loan Docs Signed'), ('settlement_conditions', 'Settlement Conditions'), ('settled', 'Settled'), ('closed', 'Closed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='inquiry', help_text='Current stage of the application', max_length=25),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the stage was last updated'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='application',
            name='uploaded_pdf_path',
            field=models.FileField(blank=True, help_text='Uploaded signed application form', null=True, upload_to='applications/signed_forms/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='valuation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valuation amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='valuation_date',
            field=models.DateField(blank=True, help_text='Date of property valuation', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='valuer',
            field=models.ForeignKey(blank=True, help_text='Selected valuer for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuer_applications', to='applications.valuer'),
        ),
        migrations.AlterField(
            model_name='application',
            name='valuer_company_name',
            field=models.CharField(blank=True, help_text='[Legacy] Valuer company name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='valuer_contact_name',
            field=models.CharField(blank=True, help_text='[Legacy] Valuer contact person name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='valuer_email',
            field=models.EmailField(blank=True, help_text='[Legacy] Valuer email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='valuer_phone',
            field=models.CharField(blank=True, help_text='[Legacy] Valuer phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, help_text='The application this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_documents', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description of the document', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('id', 'Identification'), ('income', 'Income Verification'), ('bank_statement', 'Bank Statement'), ('property', 'Property Document'), ('application', 'Application Form'), ('contract', 'Contract'), ('valuation', 'Valuation Report'), ('other', 'Other')], default='other', help_text='Type of document', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='The uploaded document file', null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the document was uploaded'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fee',
            name='application',
            field=models.ForeignKey(blank=True, help_text='The application this fee belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_fees', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, help_text='When the fee is due', null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('application', 'Application Fee'), ('valuation', 'Valuation Fee'), ('legal', 'Legal Fee'), ('broker', 'Broker Commission'), ('settlement', 'Settlement Fee'), ('other', 'Other Fee')], default='other', help_text='Type of fee', max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='invoice',
            field=models.FileField(blank=True, help_text='Invoice document for this fee', null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this fee', null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the fee', max_length=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='fundingcalculationhistory',
            name='application',
            field=models.ForeignKey(help_text='The application this calculation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='funding_calculations', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='fundingcalculationhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='fundingcalculationhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrequirement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount required for this specific purpose', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loanrequirement',
            name='application',
            field=models.ForeignKey(help_text='The application this requirement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='loan_requirements', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='loanrequirement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='loanrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrequirement',
            name='description',
            field=models.CharField(blank=True, help_text='Description of what this requirement covers', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='quantitysurveyor',
            name='address',
            field=models.TextField(blank=True, help_text='Business address', null=True),
        ),
        migrations.AlterField(
            model_name='quantitysurveyor',
            name='company_name',
            field=models.CharField(help_text='Name of the company/firm', max_length=255),
        ),
        migrations.AlterField(
            model_name='quantitysurveyor',
            name='contact_name',
            field=models.CharField(help_text='Name of the primary contact person', max_length=255),
        ),
        migrations.AlterField(
            model_name='quantitysurveyor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='quantitysurveyor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quantitysurveyor',
            name='email',
            field=models.EmailField(help_text='Primary contact email address', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='quantitysurveyor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this contact is currently active'),
        ),
        migrations.AlterField(
            model_name='quantitysurveyor',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this contact', null=True),
        ),
        migrations.AlterField(
            model_name='quantitysurveyor',
            name='phone',
            field=models.CharField(help_text='Primary contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='quantitysurveyor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Scheduled repayment amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='application',
            field=models.ForeignKey(blank=True, help_text='The application this repayment belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_repayments', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='due_date',
            field=models.DateField(blank=True, help_text='When this repayment is due', null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='invoice',
            field=models.FileField(blank=True, help_text='Invoice or receipt for this repayment', null=True, upload_to='repayment_invoices/'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this repayment', null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='paid_date',
            field=models.DateField(blank=True, help_text='When the repayment was actually paid', null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount paid', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('missed', 'Missed'), ('partial', 'Partial Payment')], default='scheduled', help_text='Current status of this repayment', max_length=10),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='address_postcode',
            field=models.CharField(blank=True, help_text='Postal code', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='address_state',
            field=models.CharField(blank=True, help_text='State/territory', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='address_street_name',
            field=models.CharField(blank=True, help_text='Street name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='address_street_no',
            field=models.CharField(blank=True, help_text='Street number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='address_suburb',
            field=models.CharField(blank=True, help_text='Suburb/city', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='address_unit',
            field=models.CharField(blank=True, help_text='Unit/apartment number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='application',
            field=models.ForeignKey(help_text='The application this property secures', on_delete=django.db.models.deletion.CASCADE, related_name='security_properties', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, help_text='Number of bathrooms', null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, help_text='Number of bedrooms', null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='building_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Building size in square meters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='car_spaces',
            field=models.PositiveIntegerField(blank=True, help_text='Number of car spaces', null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='current_debt_position',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current outstanding debt amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='current_mortgagee',
            field=models.CharField(blank=True, help_text='Current mortgage holder', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated property value', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='first_mortgage',
            field=models.CharField(blank=True, help_text='First mortgage details', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='has_carport',
            field=models.BooleanField(default=False, help_text='Whether the property has a carport'),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='has_garage',
            field=models.BooleanField(default=False, help_text='Whether the property has a garage'),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='has_off_street_parking',
            field=models.BooleanField(default=False, help_text='Whether the property has off-street parking'),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='is_single_story',
            field=models.BooleanField(default=True, help_text='Whether the property is single story'),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='land_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Land size in square meters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='occupancy',
            field=models.CharField(blank=True, choices=[('owner_occupied', 'Owner Occupied'), ('investment', 'Investment Property')], help_text='How the property is occupied', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('retail', 'Retail'), ('land', 'Land'), ('rural', 'Rural'), ('other', 'Other')], help_text='Type of property', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Property purchase price', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='second_mortgage',
            field=models.CharField(blank=True, help_text='Second mortgage details', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='valuer',
            name='address',
            field=models.TextField(blank=True, help_text='Business address', null=True),
        ),
        migrations.AlterField(
            model_name='valuer',
            name='company_name',
            field=models.CharField(help_text='Name of the company/firm', max_length=255),
        ),
        migrations.AlterField(
            model_name='valuer',
            name='contact_name',
            field=models.CharField(help_text='Name of the primary contact person', max_length=255),
        ),
        migrations.AlterField(
            model_name='valuer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='valuer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='valuer',
            name='email',
            field=models.EmailField(help_text='Primary contact email address', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='valuer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this contact is currently active'),
        ),
        migrations.AlterField(
            model_name='valuer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this contact', null=True),
        ),
        migrations.AlterField(
            model_name='valuer',
            name='phone',
            field=models.CharField(help_text='Primary contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='valuer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['reference_number'], name='application_referen_56abf0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['stage'], name='application_stage_264235_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['broker'], name='application_broker__61de8e_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['bd'], name='application_bd_id_2550af_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c6d08d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['estimated_settlement_date'], name='application_estimat_b36d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['application'], name='application_applica_824c17_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='application_documen_57c184_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='application_uploade_798c28_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['application'], name='application_applica_5e13b2_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['fee_type'], name='application_fee_typ_a099ad_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['status'], name='application_status_02d633_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['due_date'], name='application_due_dat_0fba4a_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingcalculationhistory',
            index=models.Index(fields=['application'], name='application_applica_e592cf_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequirement',
            index=models.Index(fields=['application'], name='application_applica_b1bebb_idx'),
        ),
        migrations.AddIndex(
            model_name='quantitysurveyor',
            index=models.Index(fields=['company_name'], name='application_company_8d5561_idx'),
        ),
        migrations.AddIndex(
            model_name='quantitysurveyor',
            index=models.Index(fields=['is_active'], name='application_is_acti_22e639_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['application'], name='application_applica_e142e8_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['status'], name='application_status_b5c942_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['due_date'], name='application_due_dat_825548_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['paid_date'], name='application_paid_da_0cd72b_idx'),
        ),
        migrations.AddIndex(
            model_name='securityproperty',
            index=models.Index(fields=['application'], name='application_applica_2cc3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='securityproperty',
            index=models.Index(fields=['property_type'], name='application_propert_88f107_idx'),
        ),
        migrations.AddIndex(
            model_name='securityproperty',
            index=models.Index(fields=['address_suburb', 'address_state'], name='application_address_9051b8_idx'),
        ),
        migrations.AddIndex(
            model_name='valuer',
            index=models.Index(fields=['company_name'], name='application_company_28f661_idx'),
        ),
        migrations.AddIndex(
            model_name='valuer',
            index=models.Index(fields=['is_active'], name='application_is_acti_48541c_idx'),
        ),
    ]
