# Generated by Django 4.2.7 on 2025-06-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_alter_application_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='stage_last_updated',
        ),
        migrations.AddField(
            model_name='application',
            name='stage_history',
            field=models.JSONField(default=list, help_text='History of stage changes with timestamps and users'),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('received', 'Received'), ('sent_to_lender', 'Sent to Lender/Investor'), ('funding_table_issued', 'Funding Table Issued'), ('indicative_letter_issued', 'Indicative Letter Issued'), ('indicative_letter_signed', 'Indicative Letter Signed'), ('commitment_fee_received', 'Commitment Fee Received'), ('application_submitted', 'Application Submitted'), ('valuation_ordered', 'Valuation Ordered'), ('valuation_received', 'Valuation Received'), ('more_info_required', 'More Information Required'), ('formal_approval', 'Formal Approval'), ('loan_docs_instructed', 'Loan Documents Instructed'), ('loan_docs_issued', 'Loan Documents Issued'), ('loan_docs_signed', 'Loan Documents Signed'), ('settlement_conditions', 'Settlement Conditions'), ('settled', 'Settled'), ('closed', 'Closed'), ('discharged', 'Discharged')], default='received', help_text='Current stage of the application', max_length=25),
        ),
    ]
