# Generated by Django 4.2.7 on 2025-06-23 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_remove_application_stage_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='quantity_surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.quantitysurveyor'),
        ),
        migrations.AlterField(
            model_name='application',
            name='valuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.valuer'),
        ),
    ]
