# Generated by Django 4.2.7 on 2025-06-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_alter_application_quantity_surveyor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_archived',
            field=models.BooleanField(
                default=False,
                help_text='Whether this application is archived (automatically set when stage is closed)'
            ),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_archived'], name='application_is_arch_2b9bbe_idx'),
        ),
    ] 