# Generated by Django 4.2.7 on 2025-06-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_activeloan_activeloanrepayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="Whether this application is archived (automatically set when stage is 'closed')"),
        ),
    ]
