# Generated by Django 4.2.7 on 2025-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_alter_application_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityproperty',
            name='description_if_applicable',
            field=models.TextField(blank=True, help_text="Additional description required when property_type is 'other'", null=True),
        ),
    ]
