# Generated by Django 4.2.7 on 2025-06-25 14:48

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class CheckColumnExists(Operation):
    """
    Check if a column exists in a table and only add it if it doesn't exist.
    """
    reversible = True

    def __init__(self, model_name, name):
        self.model_name = model_name
        self.name = name

    def state_forwards(self, app_label, state):
        # This operation doesn't change the state
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Check if column exists
        table_name = f"{app_label}_{self.model_name}"
        column_name = self.name
        
        # Get the list of columns in the table
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f"SELECT column_name FROM information_schema.columns "
                f"WHERE table_name = %s AND column_name = %s",
                [table_name, column_name]
            )
            exists = bool(cursor.fetchone())
        
        # Store the result for use in database_backwards
        self.column_exists = exists
        
        # If column doesn't exist, we'll let the AddField operation handle it
        # Otherwise, we'll do nothing
        return

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # No need to do anything in reverse
        pass

    def describe(self):
        return f"Check if column {self.name} exists in {self.model_name}"


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_add_description_if_applicable_to_security_property'),
    ]

    operations = [
        # First check if the column exists
        CheckColumnExists(
            model_name='application',
            name='application_already_submitted',
        ),
        # Then conditionally add the field
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_name = 'applications_application' 
                    AND column_name = 'application_already_submitted'
                ) THEN
                    ALTER TABLE applications_application 
                    ADD COLUMN application_already_submitted boolean NOT NULL DEFAULT false;
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            -- No reverse SQL needed as we're just checking if column exists
            """
        ),
    ]
