# Generated by Django 4.2.7 on 2025-06-25 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_add_application_already_submitted'),
    ]

    operations = [
        # Removed duplicate field that was already added in migration 0027
        migrations.AddField(
            model_name='application',
            name='has_other_credit_providers',
            field=models.BooleanField(blank=True, default=None, help_text='Has any application in respect of this loan been submitted by you or any other person to other credit providers?', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_credit_providers_details',
            field=models.TextField(blank=True, help_text='Details about applications submitted to other credit providers', null=True),
        ),
        migrations.AddField(
            model_name='securityproperty',
            name='first_mortgage_debt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='First mortgage debt amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='securityproperty',
            name='second_mortgage_debt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Second mortgage debt amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
