# Generated by Django 4.2.7 on 2025-06-25 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_add_mortgage_debt_fields_to_security_property'),
    ]

    operations = [
        # Removed duplicate field addition since it already exists
        migrations.AlterField(
            model_name='securityproperty',
            name='first_mortgage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='First mortgage amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='securityproperty',
            name='second_mortgage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Second mortgage amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
